import Head from "next/head";
import Hero from "@/components/hero/Hero";
import Categories from "@/components/categories/Categories";
import Benefits from "@/components/benefits/Benefits";
import Features from "@/components/features/Features";
import Process from "@/components/process/Process";
import Updates from "@/components/updates/Updates";
import Services from "@/components/services/Services";
import Footer from "@/components/footer/Footer";
import ContactUs from "@/components/contact/ContactUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hyge Rental</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="keywords"
          content="hyge rental, hygerentals, rental, rentals services"
        />
      </Head>
      <main>
        <Hero />
        <Categories />
        <Benefits />
        <Features />
        <Process />
        <Updates />
        <Services />
        <ContactUs />
        <Footer />
      </main>
    </>
  );
}
