import Head from "next/head";
import HeroSection from "@/components/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hyge Rental</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="keywords"
          content="hyge rental, hygerentals, rental, rentals services"
        />
      </Head>
      <main>
        <HeroSection />
        <h1>hello</h1>
      </main>
    </>
  );
}
